# Generated by Django 6.0.5 on 2026-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitydata',
            name='source_row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
